% CST Interface - Interface with CST from MATLAB.
% Copyright (C) 2020 Alexander van Katwijk
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <https://www.gnu.org/licenses/>.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Suppress warnings:
% Use of brackets [] is unnecessary. Use parenteses to group, if needed.
     %#ok<*NBRAK>

% This object is used to conduct the import of PCB models from 3rd-party EDA tools. To work correctly, the command methods must be executed in the order shown below.
classdef LayoutDB < handle
    %% CST Interface specific functions.
    methods(Access = ?CST.Project)
        % Only CST.Project can create a CST.LayoutDB object.
        function obj = LayoutDB(project, hProject)
            obj.project = project;
            obj.hLayoutDB = hProject.invoke('LayoutDB');
            obj.history = [];
        end
    end
    methods
        function AddToHistory(obj, command)
            obj.history = [obj.history, '     ', command, newline];
        end
    end
    %% CST Object functions.
    methods
        function SourceFileName(obj, filename)
            % Full filename of the original PCB database.
            obj.AddToHistory(['.SourceFileName "', num2str(filename, '%.15g'), '"']);
            obj.filename = filename;
        end
        function LdbFileName(obj, filename)
            % Set the filename for the CST layout database generated by the PCB import. The location is usually inside the CST project.
            obj.AddToHistory(['.LdbFileName "', num2str(filename, '%.15g'), '"']);
            obj.filename = filename;
        end
        function CreateDB(obj, addtohistory)
            % Note: MATLAB-Interface parameter addtohistory specifies whether or no to add the
            %       creation of the .ldb to the history list.
            %       By default it is not added.
            % Creates the CST layout data base file (.ldb), by importing a PCB from some 3rd-party data base format.
            obj.AddToHistory(['.CreateDB']);

            if(nargin < 2 || ~addtohistory)
                % Prepend With LayoutDB and append End With
                obj.history = [ 'With LayoutDB', newline, ...
                                    obj.history, ...
                                'End With'];
                obj.project.RunVBACode(obj.history);
                obj.history = [];
            else
                % Prepend With LayoutDB and append End With
                obj.history = [ 'With LayoutDB', newline, ...
                                    obj.history, ...
                                'End With'];
                obj.project.AddToHistory(['create LayoutDB: ', obj.filename], obj.history);
                obj.history = [];
            end
        end
        function LoadDB(obj)
            % Loads the CST layout data base file (.ldb) and creates the 3D model for it, including materials, lumped elements, and ports.
            obj.AddToHistory(['.LoadDB']);

            % Prepend With LayoutDB and append End With
            obj.history = [ 'With LayoutDB', newline, ...
                                obj.history, ...
                            'End With'];
            obj.project.AddToHistory(['import LayoutDB: ', obj.filename], obj.history);
            obj.history = [];
        end
    end
    %% MATLAB-side stored settings of CST state.
    % Note that these can be incorrect at times.
    properties(SetAccess = protected)
        project
        hLayoutDB
        history

        filename
    end
end

%% Default Settings

%% Example - Taken from CST documentation and translated to MATLAB.
