cst = actxserver('CSTStudio.Application');
project = cst.invoke('NewMWS');
brick = project.invoke('Brick');
% Do stuff with Brick
project.invoke('AddToHistory', 'Create a brick', ['With Brick', newline, ...
'.Reset', newline, ...
'.Name "brick1"', newline, ...
'.Component "component1"', newline, ...
'.Xrange "-1", "1"', newline, ...
'.Yrange "-1", "1"', newline, ...
'.Zrange "-1", "1"', newline, ...
'.Material "PEC"', newline, ...
'.Create', newline, ...
'End With']);